#![deny(unsafe_code)]

//! Rust-owned, transport-safe DTOs for desktop IPC.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub enum RuntimeModeDto {
    EmbeddedBackground,
    EmbeddedOnDemand,
    IsolatedWorker,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub enum StartupPolicyDto {
    Manual,
    OnApplicationStart,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub enum FeatureLifecycleStateDto {
    Unavailable,
    Disabled,
    Starting,
    Running,
    Degraded,
    Stopping,
    Failed,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub struct FeatureSummaryDto {
    pub id: String,
    pub display_name_key: String,
    pub description_key: String,
    pub runtime_mode: RuntimeModeDto,
    pub startup_policy: StartupPolicyDto,
    pub lifecycle_state: FeatureLifecycleStateDto,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub enum CoreRuntimeStateDto {
    Running,
    RecoveryRequired,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub struct CoreStatusDto {
    pub app_version: String,
    pub platform: String,
    pub runtime_state: CoreRuntimeStateDto,
    pub schema_version: Option<u32>,
    pub startup_error: Option<CommandErrorDto>,
    pub features: Vec<FeatureSummaryDto>,
}

/// Stable categories used by every command error envelope.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub enum CommandErrorCategoryDto {
    Validation,
    Conflict,
    Permission,
    PlatformUnsupported,
    ExternalDependency,
    Persistence,
    Migration,
    Runtime,
    Update,
    Security,
    Internal,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub struct CommandErrorDto {
    pub code: String,
    pub category: CommandErrorCategoryDto,
    pub message_key: String,
    pub recoverable: bool,
    /// Callers must supply a bounded, non-sensitive set of string values.
    pub context: BTreeMap<String, String>,
}

/// Returns the complete deterministic TypeScript binding file.
pub fn typescript_declarations() -> String {
    let declarations = [
        RuntimeModeDto::decl(),
        StartupPolicyDto::decl(),
        FeatureLifecycleStateDto::decl(),
        FeatureSummaryDto::decl(),
        CoreRuntimeStateDto::decl(),
        CoreStatusDto::decl(),
        CommandErrorCategoryDto::decl(),
        CommandErrorDto::decl(),
    ];

    let declarations = declarations.map(|declaration| {
        let declaration = match declaration.strip_prefix("export ") {
            Some(declaration) => declaration,
            None => &declaration,
        };
        format!("export {declaration}")
    });

    format!(
        "// This file is generated by crates/ipc-contracts. Do not edit manually.\n\n{}\n",
        declarations.join("\n\n")
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn error_categories_serialize_with_the_stable_wire_values() {
        assert_eq!(
            serde_json::to_string(&CommandErrorCategoryDto::PlatformUnsupported).unwrap(),
            "\"platformUnsupported\""
        );
        assert_eq!(
            serde_json::to_string(&CommandErrorCategoryDto::ExternalDependency).unwrap(),
            "\"externalDependency\""
        );
        assert_eq!(
            serde_json::to_string(&CoreRuntimeStateDto::RecoveryRequired).unwrap(),
            "\"recoveryRequired\""
        );
    }

    #[test]
    fn healthy_core_status_round_trips_with_localization_keys() {
        let status = CoreStatusDto {
            app_version: "1.2.3".to_owned(),
            platform: "windows".to_owned(),
            runtime_state: CoreRuntimeStateDto::Running,
            schema_version: Some(7),
            startup_error: None,
            features: vec![FeatureSummaryDto {
                id: "diagnostics".to_owned(),
                display_name_key: "features.diagnostics.name".to_owned(),
                description_key: "features.diagnostics.description".to_owned(),
                runtime_mode: RuntimeModeDto::EmbeddedBackground,
                startup_policy: StartupPolicyDto::OnApplicationStart,
                lifecycle_state: FeatureLifecycleStateDto::Running,
            }],
        };

        let value = serde_json::to_value(&status).unwrap();
        assert_eq!(value["runtimeState"], "running");
        assert_eq!(value["schemaVersion"], 7);
        assert!(value["startupError"].is_null());
        assert_eq!(
            value["features"][0]["displayNameKey"],
            "features.diagnostics.name"
        );
        assert_eq!(
            serde_json::from_value::<CoreStatusDto>(value).unwrap(),
            status
        );
    }

    #[test]
    fn recovery_core_status_round_trips_with_safe_startup_error() {
        let status = CoreStatusDto {
            app_version: "1.2.3".to_owned(),
            platform: "windows".to_owned(),
            runtime_state: CoreRuntimeStateDto::RecoveryRequired,
            schema_version: None,
            startup_error: Some(CommandErrorDto {
                code: "migration_required".to_owned(),
                category: CommandErrorCategoryDto::Migration,
                message_key: "errors.migration.required".to_owned(),
                recoverable: true,
                context: BTreeMap::from([("targetVersion".to_owned(), "7".to_owned())]),
            }),
            features: vec![],
        };

        let value = serde_json::to_value(&status).unwrap();
        assert!(value["schemaVersion"].is_null());
        assert_eq!(value["startupError"]["category"], "migration");
        assert_eq!(value["startupError"]["code"], "migration_required");
        assert_eq!(
            value["startupError"]["messageKey"],
            "errors.migration.required"
        );
        assert_eq!(value["startupError"]["recoverable"], true);
        assert_eq!(
            serde_json::from_value::<CoreStatusDto>(value).unwrap(),
            status
        );
    }

    #[test]
    fn structured_command_error_round_trips() {
        let error = CommandErrorDto {
            code: "invalid_feature".to_owned(),
            category: CommandErrorCategoryDto::Validation,
            message_key: "errors.feature.invalid".to_owned(),
            recoverable: true,
            context: BTreeMap::from([("featureId".to_owned(), "diagnostics".to_owned())]),
        };

        let value = serde_json::to_value(&error).unwrap();
        assert_eq!(
            serde_json::from_value::<CommandErrorDto>(value).unwrap(),
            error
        );
    }

    #[test]
    fn declarations_are_deterministic_and_contain_canonical_dtos() {
        let declarations = typescript_declarations();
        assert_eq!(declarations, typescript_declarations());
        for canonical_type in [
            "RuntimeModeDto",
            "StartupPolicyDto",
            "FeatureLifecycleStateDto",
            "FeatureSummaryDto",
            "CoreRuntimeStateDto",
            "CoreStatusDto",
            "CommandErrorCategoryDto",
            "CommandErrorDto",
        ] {
            assert_eq!(
                declarations
                    .matches(&format!("export type {canonical_type}"))
                    .count(),
                1
            );
        }
        assert!(declarations.contains("appVersion: string"));
        assert!(declarations.contains("displayNameKey: string"));
        assert!(declarations.contains("descriptionKey: string"));
        assert!(declarations.contains("runtimeState: CoreRuntimeStateDto"));
        assert!(declarations.contains("schemaVersion: number | null"));
        assert!(declarations.contains("\"platformUnsupported\""));
        assert!(declarations.contains("\"recoveryRequired\""));
        assert!(declarations.contains("messageKey: string"));
    }
}
